{
  "General Phrases": {
    'What is the word for "Hello"?': ['hola', 'salve', 'bonjour', 'hi'],
    'What is the word for "Thank you"?' : ['gracias', 'lo siento', 'cómo', 'porque'],
    'How do you say "Excuse me"?' : ['perdón','si','llamo', 'cercano'],
    'How do you ask "Where is the bathroom"?' : ['dónde está el baño', 'necesitas algo','por favor','buenos días' ],
    'How do you say "I need a telephone"?' : ['yo necesito el teléphono.','dame comida','tengo hambre','Es el amanecer' ],
    'How do you say "Yes"?':['si', 'oui','hai','yes' ],
    'How do you say "No"?': ['no','non','pero','y'],
    'What is the word for "Sorry"?':['Lo siento','Pero','Siempre','Nunca'],
    'How do you ask "Do you speak English"?':['Hablas tú inglés', 'Hablas tú americano', 'Como se dice', 'Porque ases eso'],
    'What is the word for "Please"?':['Por favor', 'Sí tu quieres','Claro','Dormir'],
  },
  "Cost/Money": {
    'How do you ask "How much is this?"?':['Cuanto cuesta esto?','Cuál es la modena?', 'Como te llamas?','Cuantos años tienes'],
    'How do you ask "Do you accept a debit card"?':['Aceptan carta de débito?','A cuanto está el dolar?','Dónde está el banco?','Cual es la hora'],
    'How do you ask "Where is the bank"?':['Dónde está el banco?','Dónde está la casa?', 'Dónde vas a la escuela','A cuanto está el dolar?'],
    'What is the word for "Money"?':['Dinero','Pesos','Oro','Modena'],
    'How do you say "I would like to withdraw money"?':['Quiero retirar dinero.','Dónde está mi dinero?', 'Cuanto dinero tengo?','Que es dinero'],
    'How do you ask "What is the currency"?':['Cual es la modena?','Cuanto cuesta esto?','Tienen espacio?','Cuantas modenas tienes?'],
    'What is the word for "Check"?':['Cheque','Carta','Papel','Cuenta'],
    'How do you say "Credit card"?'['Carta de crédito','Cree en mi','Targeta de papel','Hoja de manejo'],
    'How do you say "Seventy"?':['Setenta', 'Sesenta','Seis','Siete'],
    'How do you say "Cash"?':['Effectivo', 'Dinero', 'Débito','Cuantó'],
  },
  "Directions": {
    'How do you say "West"?':['El oeste','El este','La calle','El tren'],
    'How do you say "Left"?':['Izquierda','Derecha','Fin','Llegada'],
    'How do you ask "Where can I buy a plane ticket"?':['Dónde puedo comprar un billete de avión?','Tienes miedo a volar?','Que es un avión?','Dondé está el avión?'],
    'What is the word for "Train station"?':['La estación de tren','El supermercado','El tren está aquí','Los trenes'],
    'What is the word for "Hotel"?':['El hotel','La hotel','El motel','La motel'],
    'How do you ask "How do I get to the supermarket"?':['Como llego a el supermercado?','Como llego a la comida?','Como voy allá?','Dondé está la comida?'],
    'How do you say "Entrance"?':['Entrada','Llegada','Entro','Llego'],
    'How do you say "Exit"?':['Salida','Exito','Salir','Correr'],
    'How do you say "Where is the street"?':['Dónde está la calle?','Dónde está el piso?','Dónde está la puerta?','Dónde está el camino?'],
    'What is the word for "Traffic"?':['El tráfico','El coche','El accidente','La tráfico'],
  },
  "Time": {
    'How do you ask "What time is it"?':['Cual hora es?','Cuando empieza?','Que es el tiempo?','Estoy a tiempo?'],
    'What is the word for "Dawn"?':['El amanecer','La amanecer','Los amaneceres','Las amaneceras'],
    'What is the word for "Saturday"?':['El Sábado','La Sábado','El Sabado','La Sabado'],
    'How do you say "Am I on time"?':['Estoy a tiempo?','Estoy bien?','Estás a tiempo?','Que hora es?'],
    'How do you ask "When does the train depart"?':['A cual hora se va el tren?','Cuando llega el tren?','Dónde está el tren?','Que es un tren?'],
    'What is the word for "Yesterday"?':['Ayer','Antier','Después','Yesterdía'],
    'What is the word for "Today"?':['Hoy','Día','Ahora','Tiempo'],
    'What is the word for "Morning"?':['La mañana','El mañana','El amanecer','La amanecer'],
    'How do you say "Weekend"?':['El fin de semana','La fin de semana','El fin del día','La fin del día'],
    'How do you say "Evening"?':['La tarde','El tarde','La tárde', 'El tárde'],
  },
  "Emergencies/Medical": {
    'What is the word for "CPR"?':['RCP','PRC','RRC','PCR'],
    'What is the word for "AED"?':['DEA','ADE','EDA','EAD'],
    'What is the word for "Hospital"?':['El hospital','El ospital','La ospital','La hospital'],
    'How do you say "Where is the nearest pharmacy"?':['Dónde está la farmacia más cercana?','Dónde está la pharmacia más cercana?','Dónde está el farmacia más cercana?', 'Dónde está el pharmacia más cercana?'],
    'How do you say "Can you call the police?"?':['Puedes llamar a la policiía', 'Puedes llamar a el cop?','Puedes llamar a la officina?',"Pudes llamar a la mujer?"],
    'What is the word for "Ambulance"?':['La ambulancia', 'El ambulancia','La ambúlancia', 'El ambúlancia'],
    'How do you say "What hurts"?':['Que te duele?','Que qeuema?','Que temas?','Que te arde?'],
    'How do you say "My head hurts"?':['Me duele la cabeza','Me duele la espalda','Me duele el cabeza','Me duele el cerebro'],
    'How do you ask "Do you need help"?'['Necesitas ayuda?','Que quieres?','Algo quieres?','Ven a abrazarme'],
    'What is the word for "Doctor"?':['El doctor', 'La ayuda', 'La endermera', 'La ayudora'],
  },
  "Food": {
    'How do you ask "Are there vegan options"?':['Hay opciones veganas?','Dónde hay cominda vegana?','Te gusta cominda vegana?','Compraste cominda vegana?'],
    'What is the word for "Menu"?':['El menú','La menú', 'El ménu','La ménu'],
    'What is the word for "Vegeterian"?':['Vegetariano','Come vegetales','Vegano','Végétariano'],
    'How do you ask "What would you like to eat"?':['Que te gustaría para comer?','Que comes?','Cuales quieres?','Tienes una comida favorita?'],
    'What is the word for "Coffee"?':['El café','La cáfe','La café','El cáfe'],
    'How do you say "I would like water"?': ['Me gustría agua','Me gusta agua','Bebo agua','Amo la agua'],
    'What is the word for "Entrée"?':['El plato fuerte','La cena','La comida','El comida'],
    'What is the word for "Dessert"?':['El postre','El desierto','La galleta','La comida buena'],
    'What is the word for "Milk"?':['La leche','El leche','El leché','La leché'],
    'How do yous say "I am vegeterian"?':['Yo soy vegetariana','Yo como carne','Soy vegano','Tengo hambre'],
  },
  "Relationships": {
    'How do you say "This is my coworker"?':['Está es mi colega','Está es mis colega','Estás es mi colega','Esté es mi colega'],
    'What is the word for "Boyfriend"?':['Novio','Novío','Novía','Novia'],
    'What is the word for "Family"?';['Familia','Famili','Famila','Famelia'],
    'What is the word for "Siblings"?':['Hermanos','Señoras','Hermano','Hermanios'],
    'How do you say "I am here with my mother"?':['Estoy aquí con mi madre','Estoy aquí con mis madre','Estoys aquí con mi madre','Estoy acquís con mi madre'],
    'How do you say "These are my friends"?':['Estas son mis amigas','Estas son mis amigos','Esta es mis amigas','Esta es mis amigos'],
    'What is the word for "Father"?':['Padre','Pádre','Padres','Padrre'],
    'What is the word for "Daughter"?':['Hija','Hijo','Hijas','Híja'],
    'What is the word for "Boss"?':['Jefe','Marcó','Marco','Marcos'],
    'What is the word for "Employee"?': ['Empleado','Corregidor','Correre','Caminar'],
  },
  "Possessions": {
    'How do you say "Is this your wallet"?':['Es tu cartera?','Es tu bolsillo?','Es tu bolsa?', 'Es tú carta?'],
    'How do you say "Which is his backpack"?':['Cual es su mochila?','Cual es su mochilla?','Cual es su bolsa?', 'Cual es sus bolsa?'],
    'What is the word for "Luggage"?':['El equipaje','La equipaje', 'El equípaje','La equípaje'],
    'How do you say "This is our jewelry"?':['Está es nuestra joyería','Esto es nustro joyería','Estó es nuestra joyería','Está es nuestra joyería'],
    'What is the word for "License"?':['La liciencia','El liciencia','La líciencia','El líciencia'],
    'What is the word for "Watch"?':['El reloj','La reloj','La réloj','El réloj'],
    'How do you say "Is this their clothes"?':['Son sus ropas?','Es su ropa?','Tienes ropas?','Tienes sus ropas?'],
    'What is the word for "Purse"?':['La bolsa','El bolson','La bolson','Las bolson'],
    'What is the word for "theirs (plural)"?':['Sus','Su','Suses','Sues'],
    'What is the word for "my (singular)"?':['Mi','Mie','Mis','Mise'],
  }
}
